/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bbheaderbch_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(999c5f20ce3e05f96efa4f4616c544c9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dvbt2ll/bbheaderbch_bb.h>
// pydoc.h is automatically generated in the build directory
#include <bbheaderbch_bb_pydoc.h>

void bind_bbheaderbch_bb(py::module& m)
{

    using bbheaderbch_bb    = ::gr::dvbt2ll::bbheaderbch_bb;


    py::class_<bbheaderbch_bb, gr::block, gr::basic_block,
        std::shared_ptr<bbheaderbch_bb>>(m, "bbheaderbch_bb", D(bbheaderbch_bb))

        .def(py::init(&bbheaderbch_bb::make),
           py::arg("framesize"),
           py::arg("rate"),
           py::arg("mode"),
           py::arg("inband"),
           py::arg("fecblocks"),
           py::arg("tsrate"),
           D(bbheaderbch_bb,make)
        )
        



        ;




}








