/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(interleavermod_bc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(da51b0e102a0e35f27970022e6d492ba)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dvbt2ll/interleavermod_bc.h>
// pydoc.h is automatically generated in the build directory
#include <interleavermod_bc_pydoc.h>

void bind_interleavermod_bc(py::module& m)
{

    using interleavermod_bc    = ::gr::dvbt2ll::interleavermod_bc;


    py::class_<interleavermod_bc, gr::block, gr::basic_block,
        std::shared_ptr<interleavermod_bc>>(m, "interleavermod_bc", D(interleavermod_bc))

        .def(py::init(&interleavermod_bc::make),
           py::arg("framesize"),
           py::arg("rate"),
           py::arg("constellation"),
           py::arg("rotation"),
           D(interleavermod_bc,make)
        )
        



        ;




}








