/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pilotgenp1insert_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(04e13fb0a435f2298b8a61359025c6a4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <dvbt2ll/pilotgenp1insert_cc.h>
// pydoc.h is automatically generated in the build directory
#include <pilotgenp1insert_cc_pydoc.h>

void bind_pilotgenp1insert_cc(py::module& m)
{

    using pilotgenp1insert_cc    = ::gr::dvbt2ll::pilotgenp1insert_cc;


    py::class_<pilotgenp1insert_cc, gr::block, gr::basic_block,
        std::shared_ptr<pilotgenp1insert_cc>>(m, "pilotgenp1insert_cc", D(pilotgenp1insert_cc))

        .def(py::init(&pilotgenp1insert_cc::make),
           py::arg("carriermode"),
           py::arg("fftsize"),
           py::arg("pilotpattern"),
           py::arg("guardinterval"),
           py::arg("numdatasyms"),
           py::arg("paprmode"),
           py::arg("version"),
           py::arg("preamble"),
           py::arg("misogroup"),
           py::arg("equalization"),
           py::arg("bandwidth"),
           py::arg("vlength"),
           D(pilotgenp1insert_cc,make)
        )
        



        ;




}








