/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-dvbt2ll
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_DVBT2LL_API_H
#define INCLUDED_DVBT2LL_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_dvbt2ll_EXPORTS
#define DVBT2LL_API __GR_ATTR_EXPORT
#else
#define DVBT2LL_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_DVBT2LL_API_H */
